name: Simple Redis actions cache
description: Simple Redis actions cache
inputs:
    paths:
        description: Paths to cache
        required: true
    key:
        description: Cache key
        required: true
    redis-url:
        description: Redis connection url
        required: true
        default: redis://127.0.0.1:6379
outputs:
    cache-hit:
        description: Boolean value representing a cache hit or miss

runs:
    using: "node20"
    main: "dist/restore/index.js"
    post: "dist/save/index.js"
