on:
  push:
    branches:
      - master
  workflow_call:

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: cat /dev/random | head -c20 | base64 > hi.txt && cat hi.txt
        shell: bash
      - run: cat /dev/random | head -c20 | base64 > hello.txt && cat hello.txt
        shell: bash
      - run: cat /dev/random | head -c20 | base64 > hella.txt && cat hella.txt
        shell: bash

      - uses: ./
        id: cache-redis
        with:
          paths: |-
            hi.txt
            he*.txt
          key: hi-key
          redis-url: redis://172.21.0.0.2:6379

      - run: cat hi.txt && cat /dev/random | head -c20 | base64 > hi.txt && cat hi.txt
        shell: bash
      - run: cat hello.txt && cat /dev/random | head -c20 | base64 > hello.txt && cat hello.txt
        shell: bash
      - run: cat hella.txt && cat /dev/random | head -c20 | base64 > hella.txt && cat hella.txt
        shell: bash
